repos:
  - repo: local
    hooks:
      - id: update-repo-structure
        name: Update repository structure in README
        entry: ./scripts/update_repo_structure.sh
        language: script
        files: README.md
        stages: [ commit ]
        always_run: true